version: "3.7"

services:
 nginx:
  image: ${PROJECT_NGINX}
  container_name: "nginx"
  networks:
   - lemp-network
  ports:
   - "80:80"
   - "443:443"

 php:
  image: ${PROJECT_PHP}
  container_name: "php"
  networks:
   - lemp-network

 mysql:
  image: "mysql:5.6.40"
  container_name: "mysql"
  networks:
   - lemp-network
  environment:
   - "MYSQL_ROOT_PASSWORD=rootpassword@123"
   - "MYSQL_USER=laravel"
   - "MYSQL_PASSWORD=laravel@123"
   - "MYSQL_DATABASE=laravel_db"

 phpmyadmin:
  image: "phpmyadmin/phpmyadmin"
  container_name: "phpmyadmin"
  networks:
   - lemp-network
  ports:
   - "3333:80"
  environment:
   - "PMA_HOST=mysql"
   - "MYSQL_ROOT_PASSWORD=rootpassword@123"

networks:
 lemp-network:
  name: lamp-network
